# Generated by Django 5.1.4 on 2025-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
