# Generated by Django 5.1.4 on 2025-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_register_first_name_register_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
